### ISSUE TITLE
ReSwiftSaga maintainer

### ISSUE THREAD

**Issue by ndolgopolov** [tehjord/ReSwiftSaga#1]
Hello @jordanebelanger. according to update in the readme.md I'd like to take  over the ReSwiftSaga because I use it in my projects(I made the fork as you can see)

Best regards, Nick

**Comment by jordanebelanger** [comment]
Hey @ndolgopolov, I was hoping people who are closely involved in the ReSwift project might want to pick it up instead. I see that your fork only has 2 commits.

I am going to wait a bit longer to see if I don't have more people showing up for the repo. Thank you for your interest.
